version: '3.8'

services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: chatapp
      POSTGRES_PASSWORD: chatapp
      POSTGRES_DB: chatapp
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    restart: always
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    ports:
      - '9000:9000'   # S3 API
      - '9001:9001'   # Web UI
    volumes:
      - minio-data:/data

volumes:
  pgdata:
  minio-data:
